### ISSUE TITLE
font

### ISSUE THREAD

**Issue by ecfidler** [Quiltic/rpg-hell-frontend#15]

**Comment by ecfidler** [comment]
https://fonts.google.com/specimen/Ubuntu?query=ubuntu

**Comment by ecfidler** [comment]
https://fonts.google.com/specimen/Rubik?preview.text=MIND%20BODY%20SOUL%20mind%20body%20soul%20

**Comment by Quiltic** [comment]
https://fonts.google.com/specimen/IBM+Plex+Sans?stroke=Sans+Serif&preview.text=Here%20Lies%20the%20old%20Crab

**Comment by Quiltic** [comment]
https://fonts.google.com/specimen/Heebo?stroke=Sans+Serif&preview.text=Here%20Lies%20the%20old%20Crab

**Comment by Quiltic** [comment]
https://fonts.google.com/specimen/Lobster?stroke=Sans+Serif&preview.text=Here%20Lies%20the%20old%20Crab

Everyone Loves Lobster

**Comment by ecfidler** [comment]
Heebo
